/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "placeToairport.h"
#include "clientToplace.h"

returnPlaces *
placeserverfunct_1_svc(location *argp, struct svc_req *rqstp)
{
	static returnPlaces  result;
	printf("place server - city: %s\n", argp->city); 
	printf("place server - city: %s\n", argp->state);
	xdr_free((xdrproc_t)xdr_returnPlaces, (char*)&result);

	char* host = "localhost";
	CLIENT *clnt;
	returnAirports  *result_1;
	LatLon airportserverfunct_1_arg;
	#ifndef	DEBUG
		clnt = clnt_create (host, PLACE_TO_AIRPORT, PLACE_TO_AIRPORT_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */
	airportserverfunct_1_arg.lat = 1.1; 
	airportserverfunct_1_arg.lon = 2.2;
	result_1 = airportserverfunct_1(&airportserverfunct_1_arg, clnt);
	if (result_1 == (returnAirports *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	airportlist alist = result_1 ->returnAirports_u.list; 

	printf("succeed"); 
	placelist *head;
	placelist current;
	head = &result.returnPlaces_u.list; 
	for (int i = 0; i < 5; i++){
		current = *head = (place *)malloc(sizeof(place));
		current->distance = alist->distance; 
		head = &current->next;
		alist = alist->next;
	}
	*head = (placelist)NULL;  

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return &result;
}
