/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLIENTTOPLACE_H_RPCGEN
#define _CLIENTTOPLACE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define CODELEN 3
#define STATEMAXLEN 2
#define CITYMAXLEN 63

typedef char *codetype;

typedef char *citytype;

typedef char *statetype;

typedef struct place *placelist;

struct place {
	codetype code;
	citytype city;
	statetype state;
	double distance;
	placelist next;
};
typedef struct place place;

struct location {
	citytype city;
	statetype state;
};
typedef struct location location;

struct returnPlaces {
	int err;
	union {
		placelist list;
	} returnPlaces_u;
};
typedef struct returnPlaces returnPlaces;

#define CLIENT_TO_PLACE 0x20000014
#define CLIENT_TO_PLACE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define placeServerFunct 1
extern  returnPlaces * placeserverfunct_1(location *, CLIENT *);
extern  returnPlaces * placeserverfunct_1_svc(location *, struct svc_req *);
extern int client_to_place_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define placeServerFunct 1
extern  returnPlaces * placeserverfunct_1();
extern  returnPlaces * placeserverfunct_1_svc();
extern int client_to_place_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_codetype (XDR *, codetype*);
extern  bool_t xdr_citytype (XDR *, citytype*);
extern  bool_t xdr_statetype (XDR *, statetype*);
extern  bool_t xdr_placelist (XDR *, placelist*);
extern  bool_t xdr_place (XDR *, place*);
extern  bool_t xdr_location (XDR *, location*);
extern  bool_t xdr_returnPlaces (XDR *, returnPlaces*);

#else /* K&R C */
extern bool_t xdr_codetype ();
extern bool_t xdr_citytype ();
extern bool_t xdr_statetype ();
extern bool_t xdr_placelist ();
extern bool_t xdr_place ();
extern bool_t xdr_location ();
extern bool_t xdr_returnPlaces ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLIENTTOPLACE_H_RPCGEN */
