/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clientToplace.h"

bool_t
xdr_codetype (XDR *xdrs, codetype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, CODELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_citytype (XDR *xdrs, citytype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, CITYMAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_statetype (XDR *xdrs, statetype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, STATEMAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placelist (XDR *xdrs, placelist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct place), (xdrproc_t) xdr_place))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_place (XDR *xdrs, place *objp)
{
	register int32_t *buf;

	 if (!xdr_codetype (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_citytype (xdrs, &objp->city))
		 return FALSE;
	 if (!xdr_statetype (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_placelist (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_citytype (xdrs, &objp->city))
		 return FALSE;
	 if (!xdr_statetype (xdrs, &objp->state))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnPlaces (XDR *xdrs, returnPlaces *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_placelist (xdrs, &objp->returnPlaces_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
