/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clientToplace.h"
#include <rpc/rpc.h>

void
client_to_place_1(char *host, char *city, char *state)
{
	CLIENT *clnt;
	returnPlaces  *result_1;
	location  placeserverfunct_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CLIENT_TO_PLACE, CLIENT_TO_PLACE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	placeserverfunct_1_arg.city = city; 
	placeserverfunct_1_arg.state = state; 
	result_1 = placeserverfunct_1(&placeserverfunct_1_arg, clnt);
	if (result_1 == (returnPlaces *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	placelist list = result_1 ->returnPlaces_u.list; 
	while(list != NULL){
		//printf("code=%s, name=%s, state=%s distance: %d miles\n", list->code, list->city, list->state, list->distance);
		printf("distance: %d\n", list->distance);
		list = list->next; 
	}
	clnt_freeres(clnt, (xdrproc_t)xdr_returnPlaces, (char *)&result_1); 

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *city;
	char *state; 

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	city = argv[2]; 
	state = argv[3]; 
	client_to_place_1 (host, city, state);
	exit (0);
}
