/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "placeToairport.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

returnAirports *
airportserverfunct_1(LatLon *argp, CLIENT *clnt)
{
	static returnAirports clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, airportServerFunct,
		(xdrproc_t) xdr_LatLon, (caddr_t) argp,
		(xdrproc_t) xdr_returnAirports, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
