/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "placeToairport.h"

returnAirports *
airportserverfunct_1_svc(LatLon *argp, struct svc_req *rqstp)
{
	static returnAirports  result;
	printf("airport server succeed to receive from place server\n"); 
	printf("airport server - lat: %d \n", argp->lat);
	printf("airport server - lon: %d \n", argp->lon); 

	airportlist *head;
	airportlist current;
	head = &result.returnAirports_u.list; 
	for (int i = 0; i < 5; i++){
		current = *head = (airport *)malloc(sizeof(airport));
		current->code = strdup("ts");
		current->city = strdup("test");
		current->state = strdup("testS");  
		current->distance = 1.1; 
		head = &current->next;
	}
	*head = (airportlist)NULL; 
	return &result;
}
